version: '3.8'

services:
  gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    env_file:
      - ./gateway/.env
    volumes:
      - ./gateway:/app
      - /app/node_modules
  user-service:
    build: ./user
    ports:
      - "4001:4001"
    env_file:
      - ./user/.env
    volumes:
      - ./user:/app
      - /app/node_modules
    depends_on:
      - mongo
  cart-service:
    build: ./cart
    ports:
      - "4002:4002"
    env_file:
      - ./cart/.env
    volumes:
      - ./cart:/app
      - /app/node_modules
    depends_on:
      - mongo
  payment-service:
    build: ./payment
    ports:
      - "4003:4003"
    env_file:
      - ./payment/.env
    volumes:
      - ./payment:/app
      - /app/node_modules
    depends_on:
      - mongo
  order-service:
    build: ./order
    ports:
      - "4004:4004"
    env_file:
      - ./order/.env
    volumes:
      - ./order:/app
      - /app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
